-- Lua variables
-- Generated by 'wal'
wallpaper="/home/cinque/nextcloud-backup/Wallpaper/others/1069643-1600x900-[DesktopNexus.com].jpg"

-- Special
background="#050404"
foreground="#f1e4e0"
cursor="#f1e4e0"

-- Colors
color0="#050404"
color1="#B57787"
color2="#748CA2"
color3="#7599C7"
color4="#9E98A3"
color5="#9EB1C9"
color6="#DAB7C0"
color7="#f1e4e0"
color8="#a89f9c"
color9="#B57787"
color10="#748CA2"
color11="#7599C7"
color12="#9E98A3"
color13="#9EB1C9"
color14="#DAB7C0"
color15="#f1e4e0"

return {
    background=background,
    foreground=foreground,
    cursor=cursor,

    color0=color0,
    color1=color1,
    color2=color2,
    color3=color3,
    color4=color4,
    color5=color5,
    color6=color6,
    color7=color7,
    color8=color8,
    color9=color9,
    color10=color10,
    color11=color11,
    color12=color12,
    color13=color13,
    color14=color14,
    color15=color15,
}
